# command line: main.py recognition -c config/st_gcn/ntu-xsub/test.yaml

base_lr: 0.01
batch_size: 256
config: config/st_gcn/ntu-xsub/test.yaml
debug: false
device: 0
eval_interval: 5
feeder: feeder.feeder.Feeder
ignore_weights: []
log_interval: 100
model: net.st_gcn.Model
model_args:
    dropout: 0.5
    edge_importance_weighting: true
    graph_args:
        layout: ntu-rgb+d
        strategy: spatial
    in_channels: 3
    num_class: 60
nesterov: true
num_epoch: 80
num_worker: 4
optimizer: SGD
pavi_log: false
phase: test
print_log: true
save_interval: 10
save_log: true
save_result: false
show_topk:
- 1
- 5
start_epoch: 0
step: []
test_batch_size: 40
test_feeder_args:
    data_path: /ssd_scratch/cvit/nateshhariharan/Dataset_NTU_RGBD/xsub/test_data.npy
    label_path: /ssd_scratch/cvit/nateshhariharan/Dataset_NTU_RGBD/xsub/test_label.pkl
train_feeder_args: {}
use_gpu: true
weight_decay: 0.0001
weights: /home2/nateshhariharan/mmskeleton/deprecated/origin_stgcn_repo/models/st_gcn.ntu-xsub.pt
work_dir: ./work_dir/tmp
